### ISSUE TITLE
can not build for freebsd 386

### ISSUE THREAD

**Issue by lijiangt** [eiannone/keyboard#10]
when cross-compiling for freebsd 386, there are some error:
../vendor/github.com/eiannone/keyboard/keyboard.go:177:16: constant 2150396948 overflows int
../vendor/github.com/eiannone/keyboard/keyboard.go:211:10: constant 2150396948 overflows int

My os is ubuntu 18.04, kernel version is 4.15.0-34-generic, amd64 arch

go version go1.10.1 linux/amd64

**Comment by eiannone** [comment]
Hi @lijiangt , I have identified the cause in the wrong signature for `ioctl()` function which should take a `uint` instead of an `int` as first argument.
I now have fixed it. I have also replaced `ioctl()` and `fcntl()` functions with native ones from official "golang.org/x/sys/unix" package.
A commit for fixing this issue is coming...
