### ISSUE TITLE
keyboard.Close() freezes without keyboard input

### ISSUE THREAD

**Issue by estshorter** [eiannone/keyboard#19]
The following program, which simply calls Open() and Close(),  freezes on Windows.
``` go
package main

import (
	"fmt"
	"time"

	"github.com/eiannone/keyboard"
)

func main() {
	fmt.Println("Open begin")
	if err := keyboard.Open(); err != nil {
		panic(err)
	}
	fmt.Println("Open end")
	time.Sleep(time.Second)
	fmt.Println("Close begin")
	if err := keyboard.Close(); err != nil {
		panic(err)
	}
	fmt.Println("Close end")

}
```

output:
```
Open begin
Open end
Close begin
```
If I input any key, "Close end" is shown and the program exits.
This means that keyboard.Close() freezes.

# Environment

- OS: Windows 10 1909
- Go: go1.14.2 windows/amd64
- keyboard: 4ef8fe4c2414593fc8c538903994162019972904

**Comment by eiannone** [comment]
Hi @estshorter , I could reproduce this behaviour with cmd. I didn't notice it before because I tested the code only on poweshell, which isn't affected.
This is a regression introduced with commit 453839b3c3abc109d4ad739ef92ecb854146ccff. With latest commit ff8b964fe1c95f3ffc963fa080d60db6bee3f473 it should be fixed now.
Could you check and confirm that is solved also for you?

**Comment by estshorter** [comment]
I confirmed the fix.
Thank you @eiannone !
